export const OrderActionTypes = {
  ORDER_FETCH_SUCCESS: 'ORDER_FETCH_SUCCESS',
  SAVE_ORDER_INFO: 'SAVE_ORDER_INFO',
  SAVE_ORDER_ITEM: 'SAVE_ORDER_ITEM',
  UPDATE_ORDER_ITEM: 'UPDATE_ORDER_ITEM',
  REMOVE_ORDER_ITEM: 'REMOVE_ORDER_ITEM',
  SELECT_PRODUCT_TO_ORDER: 'SELECT_PRODUCT_TO_ORDER',
  SET_IS_SELECTING_PRODUCT: 'SET_IS_SELECTING_PRODUCT',
  SAVE_ORDER_COST: 'SAVE_ORDER_COST',
  SAVE_ORDER_RECEIVING: 'SAVE_ORDER_RECEIVING',
  SAVE_ORDER_SALE: 'SAVE_ORDER_SALE',
  SET_IS_SELECTING_CUSTOMER: 'SET_IS_SELECTING_CUSTOMER',
  SELECT_CUSTOMER_TO_ORDER: 'SELECT_CUSTOMER_TO_ORDER'
}