export const OrderActionTypes = {
  ORDER_FETCH_SUCCESS: 'ORDER_FETCH_SUCCESS',
  SAVE_ORDER_INFO: 'SAVE_ORDER_INFO',
  SAVE_ORDER_ITEM: 'SAVE_ORDER_ITEM',
  UPDATE_ORDER_ITEM: 'UPDATE_ORDER_ITEM',
  REMOVE_ORDER_ITEM: 'REMOVE_ORDER_ITEM',
  SELECT_PRODUCT_TO_ORDER: 'SELECT_PRODUCT_TO_ORDER',
  COPY_ORDER_ITEM_TO_EDIT: 'COPY_ORDER_ITEM_TO_EDIT',
  SAVE_ORDER_COST: 'SAVE_ORDER_COST',
  SAVE_ORDER_RECEIVING: 'SAVE_ORDER_RECEIVING',
  SAVE_ORDER_SALE: 'SAVE_ORDER_SALE',
  SELECT_CUSTOMER_TO_ORDER: 'SELECT_CUSTOMER_TO_ORDER',
  RESET_ORDER_EDITING: 'RESET_ORDER_EDITING',
  SET_ORDER_EDITING: 'SET_ORDER_EDITING'
}