export const OrderActionTypes = {
  ORDER_FETCH_SUCCESS: 'ORDER_FETCH_SUCCESS',
  UPDATE_CUSTOMER_TO_ORDER: 'UPDATE_CUSTOMER_TO_ORDER',
  UPDATE_SHIPPING_ADDRESS_TO_ORDER: 'UPDATE_SHIPPING_ADDRESS_TO_ORDER',
  ADD_ITEM_TO_ORDER: 'ADD_ITEM_TO_ORDER',
  UPDATE_PRODUCT_TO_ITEM: 'UPDATE_PRODUCT_TO_ITEM',
  EDIT_ORDER_ITEM: 'EDIT_ORDER_ITEM',
  UPDATE_ITEM_TO_ORDER: 'UPDATE_ITEM_TO_ORDER',
  REMOVE_ITEM_FROM_ORDER: 'REMOVE_ITEM_FROM_ORDER',
  REMOVE_ORDER_TEMPLATE: 'REMOVE_ORDER_TEMPLATE',
  COPY_TO_ORDER_TEMPLATE: 'COPY_TO_ORDER_TEMPLATE'
}