export const ProductActionTypes = {
  PRODUCT_GET_SUCCESS: 'PRODUCT_GET_SUCCESS',
  PRODUCT_PATCH_SUCCESS: 'PRODUCT_PATCH_SUCCESS',
  SET_EDITING_STYLE: 'SET_EDITING_STYLE',
  SET_NEW_PRODUCT_STYLE: 'SET_NEW_PRODUCT_STYLE',
  SET_PRODUCT_COLOR: 'SET_PRODUCT_COLOR'
}