export const ProductActionTypes = {
  PRODUCT_GET_SUCCESS: 'PRODUCT_GET_SUCCESS',
  PRODUCT_PATCH_SUCCESS: 'PRODUCT_PATCH_SUCCESS',
  PRODUCT_SET_IS_EDITING: 'PRODUCT_SET_IS_EDITING',
  SET_NEW_PRODUCT_STYLE: 'SET_NEW_PRODUCT_STYLE'
}