export const ProductActionTypes = {
  PRODUCT_FETCH_SUCCESS: 'PRODUCT_FETCH_SUCCESS',
  UPDATE_PRODUCT_STYLE: 'UPDATE_PRODUCT_STYLE',
  ADD_PRODUCT_COLOR: 'ADD_PRODUCT_COLOR',
  EDIT_PRODUCT: 'EDIT_PRODUCT'
}